version: '3.8'

services:
  app:
    build:
      context: .
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "src.app:app", "--port", "8000", "--host", "0.0.0.0", "--reload"]
    ports:
      - "80:8000"
    volumes:
      - .env:/code/.env
      - ./src:/code/src
      - ./static:/code/static
      - ./templates:/code/templates
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M